version: '3.7'

services:
  FPM:
    hostname: docker-php-fpm
    build:
      context: ./Dockerfiles/php-fpm
    image: cscolabear/7.3-fpm:0.1
    ports:
      - 9000:9000
    volumes:
      - ${VOLUMES_DRIVER}:/var/www:delegated
      - ./Dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - ./Dockerfiles/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
    extra_hosts:
      - "localhost:172.16.1.50"
      # - "any-your-project-domain:172.16.1.50"
    networks:
      app_net:
        ipv4_address: 172.16.1.40

  NODE:
    hostname: docker-node
    build:
      context: ./Dockerfiles/node
    image: cscolabear/node:latest
    ports:
      - "3000"
      - "9229:9229"
    volumes:
      - ${VOLUMES_DRIVER}:/var/www
      - ./Dockerfiles/node/pm2-process.yml:/pm2-process.yml
      - ./Logs:/var/logs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
    extra_hosts:
      - "localhost:172.16.1.50"
      # - "any-your-project-domain:172.16.1.50"
    networks:
      app_net:
        ipv4_address: 172.16.1.80

  NGINX:
    hostname: docker-nginx
    build:
      context: ./Dockerfiles/nginx
    image: cscolabear/nginx:0.1-brotli
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${VOLUMES_DRIVER}:/var/www:delegated
      - ./Logs:/var/log/nginx:delegated
      - ./Dockerfiles/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    depends_on:
      - FPM
      - NODE
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 30M
        reservations:
          memory: 10M
      restart_policy:
        condition: on-failure
    networks:
      app_net:
        ipv4_address: 172.16.1.50
        # aliases:
          # - any-your-project-domain
          # - local.project

  WORKSPACE:
    hostname: docker-workspace
    build:
      context: ./Dockerfiles/workspace
    image: cscolabear/workspace:0.2
    ports:
      - 3000:3000
    volumes:
      - ${VOLUMES_DRIVER}:/var/www
    depends_on:
      - FPM
    restart: on-failure
    extra_hosts:
      - "localhost:172.16.1.50"
      # - "any-your-project-domain:172.16.1.50"
    networks:
      app_net:
        ipv4_address: 172.16.1.30

networks:
  app_net:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.16.1.0/16
