version: '3'

services:
  fpm:
    hostname: docker-php-fpm
    build:
      context: ./Dockerfiles/php-fpm
    image: cscolabear/7.2-fpm:latest
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
      - ./Dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./Dockerfiles/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    restart: on-failure
    extra_hosts:
      - "localhost:172.16.1.50"
      # - "any-your-project-domain:172.16.1.50"
    networks:
      app_net:
        ipv4_address: 172.16.1.40

  mysql:
    hostname: docker-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    restart: on-failure
    networks:
      - app_net

  nginx:
    hostname: docker-nginx
    build:
      context: ./Dockerfiles/nginx
    image: cscolabear/nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./Logs:/var/log/nginx
      - ./Dockerfiles/nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - fpm
    restart: on-failure
    networks:
      app_net:
        ipv4_address: 172.16.1.50

  workspace:
    hostname: docker-workspace
    build:
      context: ./Dockerfiles/workspace
    image: cscolabear/workspace:latest
    ports:
      - "22:22"
    volumes:
      - ./:/var/www
    depends_on:
      - fpm
    restart: on-failure
    extra_hosts:
      - "localhost:172.16.1.50"
      # - "any-your-project-domain:172.16.1.50"
    tty: true
    networks:
      app_net:
        ipv4_address: 172.16.1.30

networks:
  app_net:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.16.1.0/16
