version: '3.7'

services:
  FPM:
    hostname: docker-php-fpm
    build:
      context: ./Dockerfiles/php-fpm
    image: cscolabear/7.2-fpm:latest
    ports:
      - 9000:9000
    volumes:
      - ${VOLUMES_DRIVER}:/var/www:delegated
      - ./Dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - ./Dockerfiles/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
    extra_hosts:
      - "localhost:172.16.1.50"
      - "local.rainy-to-do-app-api:172.16.1.50"
      - "local.news-notification:172.16.1.50"
      # - "any-your-project-domain:172.16.1.50"
    networks:
      app_net:
        ipv4_address: 172.16.1.40

  NGINX:
    hostname: docker-nginx
    build:
      context: ./Dockerfiles/nginx
    image: cscolabear/nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${VOLUMES_DRIVER}:/var/www:delegated
      - ./Logs:/var/log/nginx:delegated
      - ./Dockerfiles/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    depends_on:
      - FPM
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 30M
        reservations:
          memory: 10M
      restart_policy:
        condition: on-failure
    networks:
      app_net:
        ipv4_address: 172.16.1.50

  WORKSPACE:
    hostname: docker-workspace
    build:
      context: ./Dockerfiles/workspace
    image: cscolabear/workspace:latest
    ports:
      - "3000"
    volumes:
      - ${VOLUMES_DRIVER}:/var/www:delegated
    depends_on:
      - FPM
    restart: on-failure
    extra_hosts:
      - "localhost:172.16.1.50"
      - "local.rainy-to-do-app-api:172.16.1.50"
      - "local.news-notification:172.16.1.50"
      # - "any-your-project-domain:172.16.1.50"
    networks:
      app_net:
        ipv4_address: 172.16.1.30

  JENKINS:
    hostname: docker-jenkins
    image: jenkinsci/blueocean
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./jenkins_data/nm_cache:/var/nm_cache
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

networks:
  app_net:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.16.1.0/16
